In [1]:
from extruder import Extruder
import numpy as np
import seaborn as sns
import h5py

### Translocating and writing trajectories using custom extruder class

In [10]:
N = 500
occupied = np.zeros(N)
occupied[0] = 1
occupied[-1] = 1
steps = 200
steps_occupation = []
LEFNum = 2
num_chunks = 50

### Blockers (i.e. CTCF) - {pos. : prob.}
left_blockers_capture = {100:0.9}
right_blockers_capture = {300:0.9}
left_blockers_release = {100:0.02}
right_blockers_release = {300:0.02}



e1 = Extruder(leg1 = 175,
             leg2 = 175+1,
             ebf1 = False,
             left_blockers_capture = left_blockers_capture,
             right_blockers_capture = right_blockers_capture,
             left_blockers_release = left_blockers_release,
             right_blockers_release = right_blockers_release,
             extrusion_occupancy = occupied,
             lifetime = 10e7)
e2 = Extruder(leg1 = 250,
             leg2 = 250+1,
             ebf1 = False,
             left_blockers_capture = left_blockers_capture,
             right_blockers_capture = right_blockers_capture,
             left_blockers_release = left_blockers_release,
             right_blockers_release = right_blockers_release,
             extrusion_occupancy = occupied,
             lifetime = 10e7)
outf = "trajectory/LEFPositions.h5"
with h5py.File(outf, mode='w') as f:
    dset = f.create_dataset("positions", 
            shape=(steps, LEFNum, 2), 
            dtype=np.int32, 
            compression="gzip")
    bins = np.linspace(0, steps, num_chunks, dtype=int)
    for st,end in zip(bins[:-1], bins[1:]):
        cur = []
        for i in range(st,end):
            occupied = e1.translocate(occupied)
            occupied = e2.translocate(occupied)
            positions = [(extruder.leg1.pos, extruder.leg2.pos) for extruder in [e1,e2]]
            cur.append(positions)
        cur = np.array(cur)
        dset[st:end] = np.array(cur)
    f.attrs["N"] = N
    f.attrs["LEFNum"] = LEFNum

Leg 175: captured = False
Leg at 175 translocating
Leg 176: captured = False
Leg at 176 translocating
Leg 250: captured = False
Leg at 250 translocating
Leg 251: captured = False
Leg at 251 translocating
Leg 174: captured = False
Leg at 174 translocating
Leg 177: captured = False
Leg at 177 translocating
Leg 249: captured = False
Leg at 249 translocating
Leg 252: captured = False
Leg at 252 translocating
Leg 173: captured = False
Leg at 173 translocating
Leg 178: captured = False
Leg at 178 translocating
Leg 248: captured = False
Leg at 248 translocating
Leg 253: captured = False
Leg at 253 translocating
Leg 172: captured = False
Leg at 172 translocating
Leg 179: captured = False
Leg at 179 translocating
Leg 247: captured = False
Leg at 247 translocating
Leg 254: captured = False
Leg at 254 translocating
Leg 171: captured = False
Leg at 171 translocating
Leg 180: captured = False
Leg at 180 translocating
Leg 246: captured = False
Leg at 246 translocating
Leg 255: captured = False
Leg a

In [11]:
with h5py.File("trajectory/LEFPositions.h5", mode='r') as f:
    pos = f['positions']
    print(pos[:,:,:])

[[[174 177]
  [249 252]]

 [[173 178]
  [248 253]]

 [[172 179]
  [247 254]]

 [[171 180]
  [246 255]]

 [[170 181]
  [245 256]]

 [[169 182]
  [244 257]]

 [[168 183]
  [243 258]]

 [[167 184]
  [242 259]]

 [[166 185]
  [241 260]]

 [[165 186]
  [240 261]]

 [[164 187]
  [239 262]]

 [[163 188]
  [238 263]]

 [[162 189]
  [237 264]]

 [[161 190]
  [236 265]]

 [[160 191]
  [235 266]]

 [[159 192]
  [234 267]]

 [[158 193]
  [233 268]]

 [[157 194]
  [232 269]]

 [[156 195]
  [231 270]]

 [[155 196]
  [230 271]]

 [[154 197]
  [229 272]]

 [[153 198]
  [228 273]]

 [[152 199]
  [227 274]]

 [[151 200]
  [226 275]]

 [[150 201]
  [225 276]]

 [[149 202]
  [224 277]]

 [[148 203]
  [223 278]]

 [[147 204]
  [222 279]]

 [[146 205]
  [221 280]]

 [[145 206]
  [220 281]]

 [[144 207]
  [219 282]]

 [[143 208]
  [218 283]]

 [[142 209]
  [217 284]]

 [[141 210]
  [216 285]]

 [[140 211]
  [215 286]]

 [[139 212]
  [214 287]]

 [[138 213]
  [214 288]]

 [[137 213]
  [214 289]]

 [[136 213]
